### ISSUE TITLE
Selsame Textdarstellung

### ISSUE THREAD

**Issue by Peggy17176** [ThKattanek/emu64#138]
Beim manuellen verschieben der Fenstergröße ist der Text im Emulator Fenster seltsam dargestellt.
Text ist "ausgefranst" teilweise scheinen Pixel von Textzeichen zu fehlen (Siehe 6 im Screenshot).
Wird nochmals die Fenstergröße veränder ist es fast wieder weg.
![e64](https://user-images.githubusercontent.com/37942296/38153901-5ad864ee-346f-11e8-8559-24e6bec9c77a.JPG)

**Comment by ThKattanek** [comment]
Hi Peggy,
das ist Normal da beim manuellen ändern der Größe meist kein Gerades Teilungsverhältnis raus kommt. Damit gehen natürlich Pixel verloren oder müssen gedoppelt werden aber nicht jedes sondern z.b. jedes 3. oder 4. Pixel. Das ist Mathematisch nicht zu änder außer man nimmt immer ein Vielfaches. Also durch 2, 4, ... oder mal 2,4,8 usw. Aber man kann das optisch vertuschen wenn man den Filter aktiviert der das ganze dann glättet. Ohne Filter geht halt nur wenn man die Anzahl der originalen Pixel in X bzw. Y Richtung immer wieder verdoppelt. Also bei einer originalen breite von 384 geht dann nur 768,1536, ... usw. alles andere dazwischen gehen Pixel verloren oder müssen 2x gesetzt werden. Deshalb gibt es ja die Filter auch bei Texturen in 3D.
![screenshot_20180331_135937](https://user-images.githubusercontent.com/14269404/38162963-c61585f8-34eb-11e8-8b3d-13d7e4f7902c.png)
Ohne aktivierten Filter ...
![screenshot_20180331_135722](https://user-images.githubusercontent.com/14269404/38162955-ab1f0832-34eb-11e8-8e5c-c8c78a72d760.png)
Mit aktivierten Filter ...
![screenshot_20180331_135828](https://user-images.githubusercontent.com/14269404/38162958-b03069ba-34eb-11e8-8188-35568e8c6fa0.png)

**Comment by ThKattanek** [comment]
Nicht änderbar !
