### ISSUE TITLE
Escape Taste funktioniert nicht

### ISSUE THREAD

**Issue by RikkOOdO** [ThKattanek/emu64#167]
Hallo, ich bin's mal wieder.
Ich hatte ja ursprünglich das Problem, dass die Escape-Taste in der alten Version (4.301) von Emu64 mit dem Softrest belegt war. Deshalb konnte ich Programme, die diese benötigen, nicht nutzen. Das ist jetzt in den neuesten Versionen anders (Taste F12). Nachdem ich jetzt weiß warum Emu64 bei mir immer abstürzte, und ich dieses Problem beheben konnte, zeigt sich nun, dass in dem Programm (ein Spiel welches die Escape Taste benötigt) die Escape Taste scheinbar nicht funktioniert. Jedenfalls zeigt das Spiel keine Reaktion beim drücken der Taste. In CCS64 und VICE funktioniert das einwandfrei. Ich weiß nicht ob du die Escape-Taste nicht magst, aber ich habe meine Problem damit. Liegt das wieder an meinem System oder an Emu64?

**Comment by ThKattanek** [comment]
Es liegt an keinem. Welche C64 Taste liegt denn auf der ESC Taste bei den Emulatoren. Ich glaube die RUN/STOP oder? Du kannst dir die Tasten im Emu64 selber zuweisen wie du möchtest. Ich habe dazu mal ein Video gemacht. https://www.youtube.com/watch?v=bBdJ51BbgCA&t=5s

Unter dem Menüpunkt "Hilfe->C64 Tastenbelegung anzeigen" kannst du dir das aktuelle Mapping anzeigen. Die Belegung wird in der emu64.ini abgespeichert. Also du hast hier komplett freie Auswahl wie du dir die Tasten belegst. Nur die F11 (noch F9) und F12 sind schon mit Screenshot und Reset belegt.

**Comment by ThKattanek** [comment]
![Screenshot_20190829_202102](https://user-images.githubusercontent.com/14269404/63966031-b3b0e600-ca9a-11e9-997e-46cd435be4e2.png)
![Screenshot_20190829_202139](https://user-images.githubusercontent.com/14269404/63966032-b4497c80-ca9a-11e9-94a9-08152cf5cf44.png)

**Comment by RikkOOdO** [comment]
Ah, ok, verstehe. Also die Escape Taste ist also die Tab-Taste. Ja jetzt funktioniert's auch. Blöd nur das ich auch die Tab Taste brauche. Also ich sehe schon, das erfordert ein umfangreicheres um-Mapping des Keyboards. Ich spreche da nur für mich, aber es währe schon schön, wenn sich das Keymapping den anderen Emulatroren angleichen würde. Ist aber nur meine Meinung. Danke für die Hilfe

**Comment by ThKattanek** [comment]
Genau aus diesen Grund kann sich das jeder so einstellen wie er mag. Deshalb habe ich diese Funktion eingebaut. Und Mal ehrlich so einfach geht das in keinen anderen Emu.

**Comment by RikkOOdO** [comment]
Ok, also der Tip hätte mir am Anfang unserer gesamten Konversation sehr viel geholfen. Das die Tab-Taste = Escape-Taste ist, was auch in der alten Version 4.301 gilt. Hab ich gerad getestet. Die werd ich nun doch wieder benutzen, da ich dann nicht mein Windows-Layout umstellen muss.

**Comment by ThKattanek** [comment]
Na dann ist doch alles Supi!
