### ISSUE TITLE
Ghost dots

### ISSUE THREAD

**Issue by Zirias** [ThKattanek/emu64#197]
Für irgendwann später, weil ich gerade drüber gestolpert bin, dass ein versehentlicher "ghost dot" in emu64 nicht sichtbar wurde, hier ein Testcase:
https://csdb.dk/release/?id=82394

Eigentlich natürlich nur relevant, wenn man Emu64 zum debuggen von eigenem Code einsetzen will, also gerne schließen, falls du das einfach nicht emulieren willst :)

**Comment by ThKattanek** [comment]
Ist schon seit einiger Zeit eingebaut. Schau mal unter Einstellungen / Emulation nach ;)
![grafik](https://user-images.githubusercontent.com/14269404/84071785-936d6a80-a9ce-11ea-9fdc-ef9d76289878.png)

**Comment by Zirias** [comment]
Ok, ich war zu blöd/blind das UI zu verstehen und hab nur direkt im "Grafik" Reiter gesucht ;) Sorry :D
