### ISSUE TITLE
Turbo Assembler 7.4 claims non existing errors

### ISSUE THREAD

**Issue by snoopy78** [ThKattanek/emu64#215]
Hi Thorsten

I tried to write a simple program with the turbo assembler, but on EMU64 it claims, that the program code is not well formed.
Example is from https://www.retro-programming.de/programming/benotigte-tools/turbo-assembler/
If I try it with vice, the code is analysed well and works, so I assume, that EMU64 has troubles to work well with the assembler.

The disk image with the assembler could be downloaded from the linked website. Could you send an image from the program, if necessary (have not found a possiblity at attach something).

Sincerely, Markus from Switzerland

![Screenshot_20220222_184013](https://user-images.githubusercontent.com/14269404/155192028-92ecb2f6-d8b5-44c9-a51e-f147a3b8dbf5.png)

**Comment by ThKattanek** [comment]
Hallo Markus,

ich mach einfach mal in Deutsch weiter. Kann zwar etwas Englisch aber in deutsch geht es besser und schneller. Ich habe mal das ganze versucht nachzustellen und bei mir funktioniert das einfache Programm ohne Probleme. Habe das ganze mit der offiziellen Version 5.0.19 getestet. Oder meinst du einen Anderen Quellcode?

![emu64_4](https://user-images.githubusercontent.com/14269404/155006381-7057e753-f238-4923-b058-c0e005f7f637.png)
![emu64_5](https://user-images.githubusercontent.com/14269404/155006407-2870632d-5d19-4184-962e-b3c36bdcdbef.png)
![emu64_6](https://user-images.githubusercontent.com/14269404/155006412-31a102b8-f34f-4381-a6bf-c2109b170522.png)

**Comment by snoopy78** [comment]
Hallo Thorsten

Das ist komisch. Ich habe die Win64-Version heruntergeladen und im
Verzeichnis ausgeführt, nachdem es mit der 5.0.18 den gleichen Fehler gab.
Kann ich das irgendwie analysieren? Bei mir macht er sofort nach der
Eingabe einen Fehler.

Gruss, Markus

Thorsten Kattanek ***@***.***> schrieb am Mo., 21. Feb. 2022,
19:00:

**Comment by ThKattanek** [comment]
Ich habe jetzt das ganze auch mal unter Win10 x64 getestet und auch hier kann ich das leider nicht nachstellen. Ich glaube dir aber an der Stelle. Kannst du mir mal genau beschreiben wie es zu diesem Fehler kommt. Evtl. den Quellcode per d64 schicken. 
Oder ein kleines Video dazu.

**Comment by snoopy78** [comment]
Hallo Thorsten

Ich weiss nicht, woran es liegen könnte. Habe entsprechend ein kleines
Filmchen gemacht. Evtl. entdeckst Du ja einen Fehler.

Gruess, Markus Grob

Turbo-Assembler.7z
https://dormakabaext.egnyte.com/dl/EVdXF8gjvc
Password:8QS4frb3

Am Di., 22. Feb. 2022 um 07:37 Uhr schrieb Thorsten Kattanek <
***@***.***>:

**Comment by ThKattanek** [comment]
Echt komisch. Habe das jetzt mal auf WIn 11 mit der Version von hier nochmal getestet. Ich bekomme das einfach nicht nachgestellt. Kannst du mir mal deine emu64.ini schicken? Die liegt im $USER\.config.\emu64. Aber durch das Video sehe ich zumindest was bei dir passiert.

**Comment by snoopy78** [comment]
Hallo Thorsten

Sorry, kommt etwas spät.

Gruss aus der Schweiz, Markus

Am Di., 22. Feb. 2022 um 18:36 Uhr schrieb Thorsten Kattanek <
***@***.***>:

**Comment by snoopy78** [comment]
Hallo Thorsten

Leider war das Mail schon weg, als mir die Idee kam, die ini einfach
umzubenennen und es nochmals zu testen. Das hat entsprechend funktioniert.
Scheint daher etwas in der ini durcheinander gekommen zu sein. Ich schaffe
es nun zwar nicht mehr, die Datei abzuspeichern, weil er ein 74, drive not
ready dringt, obwohl das image eingelegt ist, doch das bekomme ich auch
noch hin ;-)

Gruss, Markus

Am Mi., 23. Feb. 2022 um 21:07 Uhr schrieb Markus Grob <
***@***.***>:

**Comment by ThKattanek** [comment]
Super. Dann geht es also erstmal soweit. Dann kann ich ja hier erstmal zu machen oder?

**Comment by snoopy78** [comment]
Hallo Thorsten

Natürlich. Evtl. kannst Du noch bei Gelegenheit schauen, welche Einstellung
das Problem verursachte.

Gruss, Markus

Thorsten Kattanek ***@***.***> schrieb am Fr., 25. Feb. 2022,
18:23:

**Comment by ThKattanek** [comment]
Kannst du mir die umbenannte ini schicken. Hoffe du hast sie noch :)

**Comment by snoopy78** [comment]
Hallo Thorsten

Klar. Die neu generierte und die originale.

Gruess, Markus Grob

Am Sa., 26. Feb. 2022 um 10:23 Uhr schrieb Thorsten Kattanek <
***@***.***>:

**Comment by snoopy78** [comment]
Hallo Thorsten

Ich vermute, dass mir der TurboAssembler die Disk "verschossen" hat. Weisst
Du, wo ich das Problem platzieren kann? Ich möchte eigentlich nicht Dich
als Entwickler belästigen.
Es schaut aber danach aus, dass der TA die Files speichert, doch jetzt der
Emu die Disk nicht mehr laden kann, weil das falsch gespeichert wurde.
Wenn ich den Eintrag manuell doppelklicke, dann kann ich ihn normal laden.
[image: load-error.png]


Am So., 27. Feb. 2022 um 20:46 Uhr schrieb Markus Grob <
***@***.***>:

**Comment by ThKattanek** [comment]
Behoben wurde das ganze durch das löschen der emu64.ini. Meine Vermutung ist die, das evtl. das Tastatur Mapping da zwischen gefunkt hat. Aber am Ende nur eine Vermutung.
