### ISSUE TITLE
commandline options für testbench

### ISSUE THREAD

**Issue by mrdudz** [ThKattanek/emu64#219]
Hy!

Um besser (bzw überhaupt) mit der VICE Testbench zu funktionieren wären folgende Kommandozeilen-Optionen noch super:

--console um ohne jeden screenoutput zu laufen (zur not geht auch minimized, ganz ohne wäre aber schöner)
--palette um eine bestimmte palette auszuwählen (damit Screenshots vergleichbar werden)
--filter um den CRT filter zu deaktivieren (ebenso)

(wie du die nennst ist natürlich egal :))

Weiterhin ist ein Screenshot, der beim Verlassen automatisch mit --exitscreenshot generiert wird, offenbar nicht mit dem angezeigten Bild identisch, das kann man zb mit den als "selftest" bezeichneten Test [*] nachvollziehen. Wenn man den Emu so aufruft wie es die Testbench tut:

```
emu64.exe --warp --debugcart --nosplash --minimized --limitcycles 10000000 --exitscreenshot c64-pass.prg-emu64.png --autostart c64-pass.prg
```

dann ist im Screenshot noch der halbe Rahmen blau - was er aber nicht sein sollte. Das verwundert etwas, weil das bei jedem anderen Emu funktioniert :) Ich rate mal das du zwischen Emulation und GUI einen Buffer hast für die Videodaten, und die ein bischen der Emulation "hinterherhinken" - beim exitscreenshot müsste also erstmal der Buffer komplett "geleert" werden bevor der Screenshot erzeugt wird.

Insbesonders letzteres verhindert derzeit dass man die Testbench überhaupt auf Emu64 loslassen kann - was ich wirklich gerne mal wieder tun würde :)

[*] Der Test liegt hier: https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/testbench/selftest/

**Comment by ThKattanek** [comment]
Hi,
werde ich mir alles ansehen und versuchen es Zeitnah zu implementieren. Die Option --minimized gibt es schon, werde aber versuchen das nur ausgaben über die Konsole kommen. Glaube es gibt dafür schon ein Issue (noGui oder so :P )
Mit dem Screenshot schaue ich mir auch an, ich glaube ich warte wirklich bis ein komplettes Bild fertig ist :) Werde ich dafür beheben, also das bei --exitscreenshot der wirklich aktuelle Stand ausgegeben wird.

**Comment by ThKattanek** [comment]
Kleine Frage noch. Möchtest du bei --palette eine pal-datei übergeben oder nur sagen welche von Emu64 genutzt werden soll als 1 - x und 0 für die Userpalette z.b. ?

**Comment by mrdudz** [comment]
Es reicht eine definierte Palette auswählen zu können, welche das ist ist eigentlich egal, die bring ich dann dem Tool bei das die Screenshots vergleicht (bzw muss ich garnicht, wenn ich zb Pepto auswählen kann)

**Comment by ThKattanek** [comment]
Ok dann weiß ich Bescheid. Ja Pepto ist schon enthalten. Video CRT kann man jetzt mit --video-filter-off temporär abschalten.

**Comment by ThKattanek** [comment]
Jetzt der Exit Screenshot. Bei mir ist das sporadisch, Vor allem sieht das sehr komisch aus, als wenn bei der Konvertierung was schief läuft. Hab das unter Linux getestet und dann noch die windows version mit wine.
*Merkwürdig
![c64-pass prg-emu64_0](https://user-images.githubusercontent.com/14269404/158891553-8072fc08-99a4-487b-bdb6-a3a539d4a5e5.png)
*Scheinbar OK
![c64-pass prg-emu64_1](https://user-images.githubusercontent.com/14269404/158891557-92ea8856-d63c-4f50-86a5-33f04b4bbddc.png)

**Comment by ThKattanek** [comment]
Wird das selbe Problem sein. Dachte auch erst das es vom umschalten der Farbe kommt. Aber meine Screenshots sehen eher nach einem Konvertierungsproblem aus, aber warum mitten im Frame. Das schaue ich mir dann Morgen Abend an was da los ist. Aber prinzipiell hatte es ja mal funktioniert, zumindest wo ich es damals implementiert hatte. Muss mal schauen ob ich danach mal was am Screenshot gefrimelt hatte.

**Comment by ThKattanek** [comment]
Auf mein Lappi sieht das so aus, ohne Angabe eines prg's. Eindeutig Konvertierungsfehler.
![c64-pass prg-emu64](https://user-images.githubusercontent.com/14269404/158897509-6f720e57-08e2-4b81-9349-e5765c56b842.png)

**Comment by ThKattanek** [comment]
Fehler gefunden und gefixt. Ich habe das jetzt einige male durchgespielt und immer waren die Shots ok. Kannst du das bitte bei dir mal testen und mir ne Rückmeldung geben :)

![c64-pass prg-emu64](https://user-images.githubusercontent.com/14269404/159131452-bc8ce6fd-9238-4316-9300-d681f791f918.png)

**Comment by mrdudz** [comment]
Das scheint korrekt zu sein jetzt!

Nun sehe ich aber gleich noch ein Problem - eventuell habe ich die Option übersehen: Der Screenshot ist um Faktor 2 skaliert, ich brauche aber den unskalierten Screen. Wenn ich mich recht erinnere war das auch mal so :)

**Comment by ThKattanek** [comment]
Ja stimmt da war was. Zur Not kannst du das direkt im Emu64 einmal abschalten "Texturgröße verdoppenl". Dann hält er das über die emu64.ini und  es sollten 1:1 Images raus kommen. Aber ich werde mir da mal ein Kommando ausdenken. --no-texture-double oder so ;)

**Comment by mrdudz** [comment]
Die ini resette ich ja mit Absicht jedes mal, damit da nicht aus versehen irgendwas drin steht was ich nicht haben will :) Da wäre eine Option dafür schon toll :)

**Comment by ThKattanek** [comment]
Nee is klar, kommt. Bin schon dabei :)

**Comment by ThKattanek** [comment]
Mit --double-texture-off sollte es jetzt funktionieren.
![c64-pass prg-emu64](https://user-images.githubusercontent.com/14269404/159137230-29a11f2b-322b-4df5-bb8d-51c8a7b3dfa0.png)

**Comment by mrdudz** [comment]
Funktioniert! Prima :) Wenn du noch -no-gui ranbastelst wäre es perfekt :)

**Comment by ThKattanek** [comment]
--no-gui war glaube ich etwas komplizierter umzusetzen, aber ich schaue es mir noch mal an. Wenn die Tests dann laufen, musst du mir nur noch erklären wie ich die Ergebnisse dann nutzen kann um die Emulation im Emu64 genauer hinzu bekommen. Gibt ja doch die eine oder andere Baustelle die ich gerne mal in Angriff nehmen würde :)

**Comment by ThKattanek** [comment]
Die anderen Sachen baue ich noch ein.

**Comment by mrdudz** [comment]
Nunja, du weisst dann was nicht (richtig) funktioniert.... wie du dann was fixen musst hängt natürlich davon ab was kaputt ist :) Die Tests erlauben dir in erster Linie zu erkennen ob bzw was kaputt ist, und ob irgendeine Änderung wieder was anderes unbeabsichtigt kaputt gemacht hat :)

**Comment by ThKattanek** [comment]
Das mit den Änderungen die wieder was anderes kaputt machen, kenne ich zu gut. Da kann man sich ganz schön schnell im Kreis drehen. Ja ich denke auch ich kann es gut nutzen um zu erkennen wo es noch klemmt :+1:

**Comment by ThKattanek** [comment]
Schon wieder um 2:00, aber ich denke ich habs. --nogui funktioniert bei mir und auch unter Windows. Hoffe es läuft auch stabil. Kannst ja mal testen wie es damit läuft. Wenn i.O. würde ich issue #106 zu machen.

**Comment by ThKattanek** [comment]
"Bei mir" heist Kubuntu 21.10

**Comment by ThKattanek** [comment]
Gerade noch gesehen, wenn --minimized zusammen mit --nogui übergeben wird erscheint in der Taskleiste kurz emu64. Ohne --minimized läufst völlig im Hintergrund. Das werde ich noch fixen. --minimized macht ja auch kein Sinn bei --nogui.

Ach ja wenn du --nogui benutzt braucht du --nospalsh nicht mehr. Schließt das mit ein ;)

**Comment by ThKattanek** [comment]
So das ist jetzt auch gefixt. Man kann --minimized und --nogui zusammen benutzen ohne aufblinken in der Taskleiste. So jetzt ist aber Schluss für heute. Viel Spaß beim testen.

**Comment by ThKattanek** [comment]
Werde mal die 3 anderen implementieren.
--enable-georam, --enable-reu      -> Zur Zeit sind GEORAM und REU von der Größe fest und können nicht verändert werden.
--set-sidtype <nummer>     0=MOS-6581 1=MOS-8580
Das implementieren dürfte jetzt nicht so lange dauern.

**Comment by ThKattanek** [comment]
So alle 3 Kommandos sind jetzt implementiert. Viel Spass beim Testen. Ich gehe jetzt erstmal Vitamin D tanken. :)
P.S. Commit für --set-sidtype wird hier  oben nicht angezeigt. habe statt #219 #119 im commit angegeben. :p

**Comment by ThKattanek** [comment]
Wenn alles soweit funktioniert könnte man den Issue dann hier erstmal zu machen. Neu Bugs dann in extra issues ;)

**Comment by ThKattanek** [comment]
Wenn das jemand unter Windows Testen will, habe ich die Pakete hier mal ran gehangen.
[emu64_5.0.19-25-g4c83b40_win_x64.zip](https://github.com/ThKattanek/emu64/files/8311110/emu64_5.0.19-25-g4c83b40_win_x64.zip)
[emu64_5.0.19-25-g4c83b40_win_x32.zip](https://github.com/ThKattanek/emu64/files/8311109/emu64_5.0.19-25-g4c83b40_win_x32.zip)

**Comment by mrdudz** [comment]
> Zur Zeit sind GEORAM und REU von der Größe her fest und können nicht verändert werden

Oh. Das würde ich nicht so machen - nicht wenige Programme kommen nicht damit klar wenn die REU bzw GEOram grösser als erwartet sind. Die (meissten) Tests gehen auch von 512k bzw 256k aus

**Comment by ThKattanek** [comment]
Ok. Werde das dann auch zeitnah einbauen. Werde dafür aber eigene issues anlegen.

**Comment by mrdudz** [comment]
OK, so weit eingebaut, Testbench läuft... in ner Stunde oder so gibts ein Ergebnis :)

**Comment by ThKattanek** [comment]
Hoffe du hast --minimized rausgeschmissen. Habe den im engeren Verdacht für die Abstürze. :)

**Comment by ThKattanek** [comment]
Hab's im emu64-hooks.sh gerade gesehen. :+1:

**Comment by mrdudz** [comment]
so, ist durchgelaufen, ein paar Probleme gibt es noch

georam tests schlagen fehl, georam wird nicht erkannt:
```
emu64 --reset-ini --video-filter-off --double-texture-off --set-palette 7  --enable-georam  --autostart ../memory-expansions//c64-georam-emd.prg
```
reu tests ebenso:
```
emu64 --reset-ini --video-filter-off --double-texture-off --set-palette 7 --enable-reu --autostart ../memory-expansions//c64-reu-emd.prg
```
- diverse drive tests schlagen fehl, hier ist mir nicht ganz klar warum genau. es sieht ein bischen so aus als würde das drive länger zum init/reset brauchen als es sein sollte, zb
```
emu64 --reset-ini --video-filter-off --double-texture-off --set-palette 7 --mount-disk 8 ../drive/scanner//scan35.d64 --autostart ../drive/scanner//scanner35.prg
```
der test funktioniert prinzipiell, läuft aber in einen timeout - was komisch ist, weil er das auf den andren emus nicht tut

- andere geben error und ganz ganz merkwürdige fehler, hier weiss ich garnicht was ich davon halten soll :=) zb:
```
/home/groepaz/Desktop/c64stuff/Emu64/bin/emu64 --reset-ini --video-filter-off --double-texture-off --set-palette 7 --mount-disk 8 ../drive/rpm//rpm.d64 --autostart ../drive/rpm//rpm1.prg
```

**Comment by ThKattanek** [comment]
Viel zum nachschauen aber danke für deine Hinweise, die bringen das ganze hier weiter und ich habe keine Langeweile :P

**Comment by ThKattanek** [comment]
Ich habe alle Probleme in einzelne Issues aufgeteilt. Werde hier jetzt zu machen, wegen der Übersichtlichkeit. Die neuen commandline options funktionieren ja soweit. Und für die Abstürze gibt es ja auch schon ein eigenes Issue.
