### ISSUE TITLE
Wishlist: PAL delayline emulieren

### ISSUE THREAD

**Issue by Zirias** [ThKattanek/emu64#234]
PAL-Decoder haben eine Delayline für U und V (also die Farbanteile des YUV-Signals). Das Delay ist exakt eine Rasterzeile, die Farbinformation wird also eine Zeile weiter unten verglichen/beigemischt, eigentlich dazu gedacht, Farbartefakte zu vermeiden. Auf dem C64 lässt sich das nutzen, um nahezu perfekte "Mischfarben" zu erzeugen, Voraussetzung ist, dass beide Farben gleich hell sind (gleicher Luma-Wert).

VICE kann das emulieren (und hat sogar eine Option für eine "U-only Delayline", anscheinend gibt es auch solche Decoder...). Emu64 bisher leider nicht, dadurch sind dann Streifen erkennbar wenn dieser Trick genutzt wird....

Etwas Hintergrundinfo zum Beispiel hier: https://kodiak64.com/blog/luma-driven-graphics-on-c64

**Comment by ThKattanek** [comment]
Dankeschön für das Issue. Werde das ganze mal studieren und dann sehen wie ich das umsetzten kann.  Bin gerade eh dabei  wieder hier weiter zu machen.

**Comment by Zirias** [comment]
Es ist vermutlich sehr komplex .... hier mal ein Beispiel aus einer WIP production, zunächst die pixelgenaue Darstellung:
![image](https://user-images.githubusercontent.com/5891057/226413026-e533b4de-9d01-4be6-ac3b-e94be24f5936.png)

Emu64 stellt es mit CRT-Emulation momentan so dar:
![image](https://user-images.githubusercontent.com/5891057/226413811-74f88ce0-1393-44de-94bf-e5c3561c5d5a.png)

VICE mit CRT-Emulation macht das daraus (und das entspricht der realen Darstellung auf meinem originalen 1081 Monitor, eine flächige Mischfarbe aus 3/4 "lightred" und 1/4 "green"):
![image](https://user-images.githubusercontent.com/5891057/226414201-4d170dbe-9e9d-4fde-a315-82b18c3f5d47.png)

Vermutlich geht es sogar um ein bisschen mehr als "nur" die Delayline, denn NTSC hat keine, aber horizontal mischen sich Farben da trotzdem auch ein bisschen besser (zumindest wenn ich der Emulation von VICE da vertrauen kann, habe selbst leider keine NTSC-Hardware):
![image](https://user-images.githubusercontent.com/5891057/226414686-6b6d9aeb-2d8f-4a4b-86b6-f9d7a467d996.png)

Ja, analoge Video-Signale sind ein wenig Voodoo :rofl:

**Comment by ThKattanek** [comment]
Ja das Thema ist schon sehr komplex. Habe das gemerkt als ich die CRT Emulation im Emu64 eingebaut habe. Ja die Analogwelt in die Digitale Welt zu pressen ist gar nicht mal so einfach. 😁

**Comment by Zirias** [comment]
Ich vermute der eigentliche Knackpunkt ist, dass die Auflösung der Farbsignale (U und V) geringer ist als die des Helligkeitssignals (Y). Deshalb ergibt sich oben bei der CRT-Emulation von VICE für NTSC dieses Muster mit den an- und abschwellenden gelben Linien (rot und grün addiert sich nunmal zu gelb). Und bei PAL kommt eben noch die Delayline dazu, durch die sich Farben gleicher Helligkeit auch vertikal mischen, dadurch kriegt man auf einem echten PAL-CRT "echte" Mischfarben hin, solange man eben nur Farben gleicher Helligkeit verwendet.

Ja, ich hab schon aus gutem Grund "wishlist" davorgeschrieben. Es wäre verdammt cool, diese Effekte korrekt zu emulieren (gerade wenn ich lese, dass das z.B. schon 1993 in "Mayhem in Monsterland" aktiv ausgenutzt wurde). Aber da ich selbst absolut keinen Schimmer hätte, wie ich das angehe ... ;-)

**Comment by ThKattanek** [comment]
Hast du Beispiele als prg die ich mir mal genauer ansehen kann. So kann ich mal vergleichen zwischen c64 mit 1084 und emu64 und vice. Wenn du hier nichts anhängen möchtest kannst du mir das auch als e-mail schicken.

**Comment by Zirias** [comment]
Nunja, da der von mir verlinkte Artikel das erwähnt: "Mayhem in Monsterland" ist vermutlich ein brauchbarer Testcase ;)

Was die kleinen Screenshots oben angeht, das ist noch nicht released, daher ja, das kann ich hier nicht anhängen. Ich würde deinem Wort vertrauen, es vertraulich zu behandeln, und es direkt per Mail schicken ... dazu bräuchte ich dann aber deine private Email-Adresse :-)

**Comment by ThKattanek** [comment]
Ja du kannst mir vertrauen und hast mein Wort, das bleibt bei mir und dient nur mir zu Testzwecken und wird auch nicht weitergegeben.

**Comment by ThKattanek** [comment]
Ein etwas besseres Ergebnis bekommt man wenn man den HoBlur (UV) auf 3 stellt. aber richtig gemischt ist da auch nichts. Es fällt nur das Schachbrettmuster weg. Wenn natürlich die voriger Zeile in die nächste mit rein spielt sähe das schon ganz anders aus.

**Comment by Zirias** [comment]
> Ein etwas besseres Ergebnis bekommt man wenn man den HoBlur (UV) auf 3 stellt. aber richtig gemischt ist da auch nichts.
Habe ich eben getestet. Ja, das ist vermutlich das Ergebnis, was man auf NTSC erwarten würde, also ohne die Delayline.

**Comment by ThKattanek** [comment]
Habe mir das jetzt mal genauer angesehen und habe das ganze mal überarbeitet. Die PAL Delayline ist jetzt drin und ich habe noch den UV Blur nochmal geändert. Das ganze sieht jetzt ganz gut aus, denke ich. Ich werde morgen die Delayline einstellbar machen und noch "u only" einbauen. Das ganze ist im Branch. /wish/new_crt_emulation_2. Die Delayline ist momentan "dauer an".
Hier ein Screenshot.
![1](https://user-images.githubusercontent.com/14269404/230988509-11fb28c4-0519-4eba-af6b-ff22c8067490.png)

**Comment by Zirias** [comment]
Cool, das sieht schon ziemlich realistisch aus! Anders als in VICE (etwas "streifiger"), aber vermutlich kommt es auch auf jedem realen PAL CRT ein wenig anders raus ;-)

**Comment by ThKattanek** [comment]
So die beiden Sachen kann man nun einstellen und werden auch gespeichern. Werde noch versuchen das Y-Blur zu verbessern. Das "blurt" mir noch auf "1" zu sehr.  Wenn das dann drin ist, wird es zum master gemerged. Wenn du das testen möchtest kannst du gerne den branch "new_crt_emulation_2" auschecken
![Screenshot_20230411_213209](https://user-images.githubusercontent.com/14269404/231270631-8770b0b5-78b2-499e-a542-542c5aa9d4e5.png)

**Comment by ThKattanek** [comment]
Mir fällt gerade noch ein, wenn du Zeit finden solltest das zu testen, schau mal bitte auf die Performance. Eventuell muss ich da noch was optimieren und wieder mit vor berechneten Tabellen arbeiten oder mir was anderes ausdenken. Aber prinzipiell lässt sich da bestimmt noch was an Performance raus holen. Bei mir läuft das ganze mit den Standard CRT Werten bei 2,1 - 2,2 % Cpu und die alte Version bei 1,8%.

**Comment by ThKattanek** [comment]
Y_Blur habe ich erneuert und wirkt nicht mehr so schwammig bei "doppelter Texturgröße"
links alter Y-Blur / rechts neuer Y-Blur (jeweils Einstellung "1")
![emu64_11_1](https://user-images.githubusercontent.com/14269404/232156220-2e82dbaf-0fef-4838-9f4d-60c9093ead13.png)  ![emu64_12_1](https://user-images.githubusercontent.com/14269404/232156242-2f85e3fa-d3bd-4844-a97f-1fae7aeb7f36.png)

**Comment by ThKattanek** [comment]
Diese Video CRT Einstellungen empfinde ich persönlich am besten. Werde diese wohl als "default" nehmen.
![Screenshot_20230414_232211](https://user-images.githubusercontent.com/14269404/232157293-5c1f0111-c551-48ca-a2ce-e6f906b499f2.png)

**Comment by ThKattanek** [comment]
Erledigt!

Ist jetzt im master enthalten und wird Bestandteil von 5.0.20.
